version: '3'
services:
  api:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/app
  worker:
    build:
      context: .
      dockerfile: Dockerfile-worker
    volumes:
     - .:/app
  redis:
    image: "redis:alpine"